version: '3'
services:
  genenotebook:
    build: .
    image: genenotebook:v0.1.8
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    command: ['wait-for-it.sh','mongodb:27017','--',
      'genenotebook','run','--mongo-url','mongodb://mongodb:27017']
  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017