version: '3'
services:
  genenotebook:
    image: genenotebook/genenotebook:v0.1.14
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 3000:3000 # PORT ON WHICH GENENOTEBOOK WILL BE ACCESSIBLE
    depends_on:
      - mongodb
    command: ['wait-for-it.sh','mongodb:27017','--',
      'genenotebook','run','--mongo-url','mongodb://mongodb:27017']
  mongodb:
    image: mongo
    volumes:
      - ./data/db:/data/db # FOLDER WHERE ALL DB FILES ARE STORED
    ports:
      - 27017